type: Group
instructions:
  - type: Group
    instructions:
      - type: ExecuteCommand
        command: >-
            {{.Env.PYTHON_EXECUTABLE}} -u {{.AgentWorkingDir}}/qt-creator/qt-creator/scripts/build.py
                --build-type {{.Env.QTC_BUILD_TYPE}}
                --src {{.AgentWorkingDir}}/qt-creator/qt-creator
                --build {{.AgentWorkingDir}}/qt-creator/qt-creator_build
                --qt-path {{.AgentWorkingDir}}/build/qt_install_dir
                --elfutils-path {{.AgentWorkingDir}}/build/qt_temp/elfutils
                --llvm-path {{.AgentWorkingDir}}/build/qt_temp/libclang
                {{.Env.QTC_TEST_OPTION}}
                --no-zip
                {{.Env.QTC_SCCACHE_C_OPTION}}
                {{.Env.QTC_SCCACHE_CXX_OPTION}}
                {{.Env.QTC_SCCACHE_ENABLE_OPTION}}
        maxTimeInSeconds: 36000
        maxTimeBetweenOutput: 3600
        userMessageOnFailure: "Failed to run build.py, check logs."
      - type: ExecuteCommand
        command: >-
            {{.Env.PYTHON_EXECUTABLE}} -u {{.AgentWorkingDir}}/qt-creator/qt-creator/scripts/build_sdktool.py
                --qt-url {{.Env.QTC_SDKTOOL_QT_BASE_URL}}{{.Env.QTC_SDKTOOL_QT_EXT}}
                --qt-build {{.AgentWorkingDir}}/build/sdktool/qt
                --src {{.AgentWorkingDir}}/qt-creator/qt-creator/src/tools/sdktool
                --build {{.AgentWorkingDir}}/build/sdktool/build
                --install {{.AgentWorkingDir}}/build/sdktool/install
                --make-command ninja
        maxTimeInSeconds: 36000
        maxTimeBetweenOutput: 3600
        userMessageOnFailure: "Failed to build sdktool, check logs."
    enable_if:
      condition: and
      conditions:
        - condition: property
          property: host.os
          equals_value: Linux

  - type: Group
    instructions:
      - type: ExecuteCommand
        command: >-
            {{.Env.PYTHON_EXECUTABLE}} -u {{.AgentWorkingDir}}/qt-creator/qt-creator/scripts/build.py
                --build-type {{.Env.QTC_BUILD_TYPE}}
                --src {{.AgentWorkingDir}}/qt-creator/qt-creator
                --build {{.AgentWorkingDir}}/qt-creator/qt-creator_build
                --qt-path {{.AgentWorkingDir}}/build/qt_install_dir
                --llvm-path {{.AgentWorkingDir}}/build/qt_temp/libclang
                --keychain-unlock-script /Users/qt/unlock-keychain.sh
                {{.Env.QTC_TEST_OPTION}}
                --no-zip
                {{.Env.QTC_SCCACHE_C_OPTION}}
                {{.Env.QTC_SCCACHE_CXX_OPTION}}
                {{.Env.QTC_SCCACHE_ENABLE_OPTION}}
        maxTimeInSeconds: 36000
        maxTimeBetweenOutput: 3600
        userMessageOnFailure: "Failed to run build.py, check logs."
      - type: EnvironmentVariable
        variableName: MACOSX_DEPLOYMENT_TARGET
        variableValue: "{{.Env.SDKTOOL_MACOSX_DEPLOYMENT_TARGET}}"
      - type: ExecuteCommand
        command: >-
            {{.Env.PYTHON_EXECUTABLE}} -u {{.AgentWorkingDir}}/qt-creator/qt-creator/scripts/build_sdktool.py
                --qt-url {{.Env.QTC_SDKTOOL_QT_BASE_URL}}{{.Env.QTC_SDKTOOL_QT_EXT}}
                --qt-build {{.AgentWorkingDir}}/build/sdktool/qt
                --src {{.AgentWorkingDir}}/qt-creator/qt-creator/src/tools/sdktool
                --build {{.AgentWorkingDir}}/build/sdktool/build
                --install {{.AgentWorkingDir}}/build/sdktool/install
                --make-command ninja
                --universal
        maxTimeInSeconds: 36000
        maxTimeBetweenOutput: 3600
        userMessageOnFailure: "Failed to build sdktool, check logs."
    enable_if:
      condition: property
      property: host.os
      equals_value: MacOS

  - type: Group
    instructions:
      - type: ExecuteCommand
        command: >-
            {{.Env.PYTHON_EXECUTABLE}} -u {{.AgentWorkingDir}}\qt-creator\qt-creator\scripts\build.py
                --build-type {{.Env.QTC_BUILD_TYPE}}
                --src {{.AgentWorkingDir}}\qt-creator\qt-creator
                --build {{.AgentWorkingDir}}\qt-creator\qt-creator_build
                --qt-path {{.AgentWorkingDir}}/build/qt_install_dir
                --python-path {{.AgentWorkingDir}}\build\qt_temp\python
                --add-config=-DPythonTargetx64Dll={{.AgentWorkingDir}}\build\qt_temp\python-amd64\python311.dll
                --add-config=-DPythonTargetarm64Dll={{.AgentWorkingDir}}\build\qt_temp\python-arm64\python311.dll
                --add-config=-DPythonTargetwin32Dll={{.AgentWorkingDir}}\build\qt_temp\python-win32\python311.dll
                --elfutils-path {{.AgentWorkingDir}}/buid/qt_temp/elfutils
                --llvm-path {{.AgentWorkingDir}}/build/qt_temp/libclang
                --no-zip
                {{.Env.QTC_TEST_OPTION}}
                {{.Env.QTC_SCCACHE_C_OPTION}}
                {{.Env.QTC_SCCACHE_CXX_OPTION}}
                {{.Env.QTC_SCCACHE_ENABLE_OPTION}}
        maxTimeInSeconds: 36000
        maxTimeBetweenOutput: 3600
        userMessageOnFailure: "Failed to run build.py, check logs."
      - type: ExecuteCommand
        command: >-
            {{.Env.PYTHON_EXECUTABLE}} -u {{.AgentWorkingDir}}\qt-creator\qt-creator\scripts\build_sdktool.py
                --qt-url {{.Env.QTC_SDKTOOL_QT_BASE_URL}}{{.Env.QTC_SDKTOOL_QT_EXT}}
                --qt-build {{.AgentWorkingDir}}\build\sdktool\qt
                --src {{.AgentWorkingDir}}\qt-creator\qt-creator\src\tools\sdktool
                --build {{.AgentWorkingDir}}\build\sdktool\build
                --install {{.AgentWorkingDir}}\build\sdktool\install
                --make-command ninja
        maxTimeInSeconds: 36000
        maxTimeBetweenOutput: 3600
        userMessageOnFailure: "Failed to build sdktool, check logs."
    enable_if:
      condition: property
      property: host.os
      equals_value: Windows

  - type: UploadArtifact
    archiveDirectory: "{{.AgentWorkingDir}}/qt-creator/qt-creator_build/build"
    transferType: UploadModuleBuildArtifact
    maxTimeInSeconds: 1800
    maxTimeBetweenOutput: 1800
